image: openjdk:10-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
      
build:
  stage: build
  tags:
    - dockerex
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/

test:
  stage: test
  tags:
    - dockerex
  script: ./gradlew check
  
deploy:
  stage: deploy
  tags:
    - dockerex
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull -t titan-ccp-configuration .
    - docker tag titan-ccp-configuration industrialdevops/titan-ccp-configuration:latest
    - docker tag titan-ccp-configuration industrialdevops/titan-ccp-configuration:$(date +%Y%m%d%H%M%S)
    - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_ID --password-stdin
    - docker push industrialdevops/titan-ccp-configuration
    - docker logout
  only:
    - master